version: "3.7"
services:
  web:
    image: testmailt46/simple-flask-api:version1.0
    ports:
      - "5000:5000"
    env_file:
      - ./.env
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432
