version: "3.8"
services:
  api:
    build: .
    # image: testmailt46/simple-flask-api:version1.6
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOSTNAME: db
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    depends_on:
      - db
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    # env_file:
    #   - .env
    ports:
      - "5432:5432"
    restart: always
